### ISSUE TITLE
Erro na compilação

### ISSUE THREAD

**Issue by wllsena** [jpocom/cpp_server#2]
É preciso ter a biblioteca boost para compilar o código.
É possível compilar corretamente assim:
g++ -std=c++11 server.cpp -o server -I ~/homebrew/Cellar/boost/1.69.0_2/include/ -L ~/homebrew/Cellar/boost/1.69.0_2/lib/

**Comment by jpocom** [comment]
Yes, that's true, server_http.hpp needs the asio library from boost.
